# Generated by Django 4.2.21 on 2025-05-20 03:38

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lti_launch_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ltilaunchrecord",
            name="modified",
        ),
        migrations.AlterField(
            model_name="ltilaunchrecord",
            name="created",
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
