name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        task: ["quality:check", "test:test"]
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12

      - name: Cache package
        uses: actions/cache@v4
        with:
          key: pip-${{ hashFiles('pyproject.toml', 'requirements/*') }}
          restore-keys: |
            pip-${{ hashFiles('pyproject.toml', 'requirements/*') }}
            pip-
          path: |
            ~/.cache/pip

      - name: Install hatch
        run: pipx install hatch

      - name: Run ${{ matrix.task }}
        run: hatch run ${{ matrix.task }}

      - name: Run coverage
        if: matrix.task == 'test:coverage'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
